### PR TITLE
Implement benchmark in C

### PR DESCRIPTION
**Pull request by mattjala**
For #1

### CODE REVIEW

**Review by jreadey — COMMENTED** [review]
what's attribute_iteration_test() for?

**Review by jreadey — COMMENTED** [review]
and test_get_range()?

**Comment by jreadey** [comment]
Could you add a makefile?

**Comment by mattjala** [comment]
> what's attribute_iteration_test() for?

These are functions I used to test the code while writing it. I'll clean them up and add a Makefile.

**Pull request merged**
