### PR TITLE
Benchmark times for REST VOL and ros3 VFD

### PR DESCRIPTION
**Pull request by mattjala**
Because the ros3 VFD is (as the name suggests) read-only, I benchmarked the REST VOL with and without the writing parts of `icesat2_selection.c` to get a more 1:1 comparison between them. 

New selection times can be seen in the table [here](https://github.com/mattjala/nasa_cloud/blob/c_benchmark/benchmarks/select_time.csv)

Pertinent to #14, logs tracking ros3 I/O during the benchmark can be found on the EC2 instance under `~/projects/nasa_cloud/benchmarks/C/ros3_out_paged` (for the 10MiB version) and  `~/projects/nasa_cloud/benchmarks/C/ros3_out_unpaged` (for the regular version).

### CODE REVIEW

**Comment by jreadey** [comment]
In the benchmark we are writing to a local file.  Isn't it possible to open the s3 file with ros3 and standard vfd with the local file?  Same thing with rest vol.

**Comment by mattjala** [comment]
> In the benchmark we are writing to a local file. Isn't it possible to open the s3 file with ros3 and standard vfd with the local file? Same thing with rest vol.

It is possible to read one file with ros3 and write to another with the standard VFD, I'll set that up and add the results to the table. 

The REST VOL can't write to a local file since it entirely replaces the standard HDF write functions.

**Comment by jreadey** [comment]
But you have one file handle for reading and another for writing.  You are saying you can't use different vol's for the two?

**Comment by mattjala** [comment]
> But you have one file handle for reading and another for writing. You are saying you can't use different vol's for the two?

Not to my knowledge. VOLs aren't tied to a particular file handle, but to the entire application at build time. This is why `USE_REST_VOL` is a preprocessor macro instead of being set at runtime. 

EDIT: I was incorrect - VOL usage is tied to FAPL, I just didn't realize this because I was using the environment variable `HDF5_VOL_CONNECTOR=REST`, which automatically affects FAPLs under the hood.

**Comment by mattjala** [comment]
The RV benchmarks are now recorded while it was writing to a local file.

**Review by jreadey — APPROVED** [review]

**Pull request merged**
